name: Dreamos Build

on:
  push:
    branches: [ new_workflow_test ]
  pull_request:
    branches: [ new_workflow_test ]

jobs:
  build-dreamos:

    runs-on: ubuntu-latest

    steps:

    - name: Prepare cache for binaries
      uses: actions/cache@v2
      id: cached-binaries
      with:
        path: |
          **/gcc-x86_64-cross
        key: gcc-binary-toolchains

    - name: Install llvm and clang
      run: sudo apt install lld llvm

    - name: Install nasm
      run: sudo apt install nasm

    - name: Download gcc
      if: steps.cached-binaries.outputs.cache-hit != 'true'
      run: >
        mkdir toolchains;
        wget https://toolchains.bootlin.com/downloads/releases/toolchains/x86-64/tarballs/x86-64--glibc--stable-2022.08-1.tar.bz2 -O toolchains/gcc-x86_64;
        cd toolchains;
        tar -vxf gcc-x86_64; mv x86-64--glibc--stable-2022.08-1 gcc-x86_64-cross;

    - uses: actions/checkout@v2
      with:
        path: dreamos

    - name: Compile with gcc
      run: >
        cd dreamos;
        ls;
        make clean;
        nasm -v;
        make build
        TOOLCHAIN=gcc
        IS_WORKFLOW=1
        ARCH_PREFIX=x86_64-elf
        IMAGE_BASE_NAME=DreamOS64


